# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# remove lines after this if you are not using smartir or nginx  
smartir:

climate:
  platform: smartir
  name: Ilmalämpöpumppu
  unique_id: portaat_ac
  device_code: 1129
  controller_data: remote.ilp_kaukosaadin
  #temperature_sensor: sensor.temperature
  #humidity_sensor: sensor.humidity
  #power_sensor: binary_sensor.ac_power

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16
    - 127.0.0.1
    - 192.168.86.237
    - ::1

  ip_ban_enabled: true
  login_attempts_threshold: 5
